# 1. get laptop
# 2.install python 3.11
# 3. clone my repo
# 4. requirements.txt
# 5. playwright install
# 6. allure setup
# 7. exucuting the test case
# 8. generate the report



name: playwright python automation sep 9th

#on: [push, pull_request]
#dd
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-python@v6
           
              with:
                  python-version: 3.11
            - run: pip install -r requirements.txt
            - run: playwright install
            - name: Run tests with pytest
              run: pytest -n 6 --alluredir=allure-results
              if: always()
            - run: |
                sudo apt-get update
                sudo apt-get install -y unzip wget
                 wget -q https://github.com/allure-framework/allure2/releases/download/2.46.1/allure-2.46.1.zip

                unzip -q allure-2.46.1.zip

                sudo mv allure-2.46.1 /opt/allure

                sudo ln -sf /opt/allure/bin/allure /usr/local/bin/allure
              if: always()
            - run: allure generate allure-results -o allure-report --clean
            
            - name: Deploy Allure Report to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              if: always()
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh-pages
                publish_dir: allure-report